name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.12-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics check_port_connectivity"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pytest-timeout

    - name: Check code style with black
      run: black --check .

    - name: Check code style with flake8
      run: flake8 .

    - name: Wait for RabbitMQ to be ready
      run: |
        echo "Waiting for RabbitMQ..."
        for i in {1..20}; do
          nc -z localhost 5672 && curl -u guest:guest http://localhost:15672/api/overview && echo "RabbitMQ is up!" && break
          echo "Waiting..."
          sleep 3
        done

    - name: Run tests
      run: pytest tests/ -v --timeout=30
